#! /bin/bash
: ${DISTROS:="$HOME/distros"}
export DISTROS
export OIFS=$IFS
export IFS='
'
list(){
	for line in $(cat $DISTROS)
		do display
	done
	}
display(){
	echo "$(echo "$line" | cut -f1 -d'^' -) version $(echo "$line" | cut -f2 -d'^' -) is on LXFDVD number $(echo $line | cut -f3 -d '^' -)"
}
finddvd(){
	echo "Which distro are you looking for?"
	read distro
	for line in $(grep $distro $DISTROS);
		do display
	done
}
finddistro(){
	echo "Which DVD are you looking for distros on?"
	read dvd
	for line in $(grep $dvd $DISTROS);
		do display
	done
}
add(){
	echo "Which distro are you adding?"
	read distro
	echo "Which version is it?"
	read version
	echo "Which DVD is it on?"
	read dvd
	echo -n "$distro" >> $DISTROS
	echo -n '^' >> $DISTROS
	echo -n "$version" >> $DISTROS
	echo -n '^' >> $DISTROS
	echo "$dvd" >> $DISTROS
	sort $DISTROS -o $DISTROS
}
remove(){
	echo "Which distro are you removing?"
	read distro
	echo "Which version is it?"
	read version
	echo "Which DVD is it on?"
	read dvd
	for line in $DISTROS
		do removethis=$(echo $line | grep $distro | grep "$version" | grep "$dvd")
		display removethis
		echo "Are you SURE you want to remove this distro? (y/N)"
		read input
		if [ "$input" = "y" ] || [ "$input" = "Y" ]
			then grep -v "$line" $DISTROS > /tmp/foo$$
			mv /tmp/foo$$ $DISTROS
			sort $DISTROS -o $DISTROS
		fi
	done
}
reset(){
	echo "Are you SURE you want to reset the database? (y/N)"
	read input
	if [ "$input" = "y" ] || [ "$input" = "Y" ]
		then echo - '' > $DISTROS
	fi
}
main(){
	while true
		do echo "What do you want to do?"
		echo '1: read-only operations'
		echo '2: edit the database'
		echo 'q: quit'
		read choice
		case $choice in 
		1)
			ro;;
		2)
			rw;;
		q)
			exit;;
		*)
			echo 'Type 1, 2 or q to quit.'
		esac
	done
}
ro(){
	while true
		do echo '1: list all distros'
		echo '2: find which DVD a distro is on'
		echo '3: list the contents of a DVD'
		echo 'q: go back'
		read choice
		case $choice in 
		1)
			list;;
		2)
			finddvd;;
		3)
			finddistro;;
		q)
			break;;
		*)
			echo 'Type 1, 2, 3, or q to go back.'
		esac
	done
}
rw(){
	while true
		do echo '1: add a distro'
		echo '2: remove a distro'
		echo '3: reset the database'
		echo 'q: go back'
		read choice
		case $choice in 
		1)
			add;;
		2)
			remove;;
		3)
			reset;;
		q)
			break;;
		*)
			echo 'Type 1, 2, or q to go back.'
		esac
	done
}
main
